# Generated by Django 4.1.3 on 2022-11-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='Имя сотрудника')),
                ('task_name', models.CharField(max_length=100, verbose_name='Текст задачи')),
                ('per_day', models.PositiveIntegerField(default=1, verbose_name='Количество напоминаний за 1 день')),
            ],
        ),
    ]
